# --- NEUTRALIZAÇÃO ---

MATCHUP_ATACANTE_VS_ZAGUEIRO = [
    {'stat_adversario': 'goals', 'stat_meu_jogador': 'goalsConceded', 'sentido': 'inverso'},
    {'stat_adversario': 'bigChancesCreated', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'totalShots', 'stat_meu_jogador': 'blockedShots', 'sentido': 'direto'},
    {'stat_adversario': 'totalShots', 'stat_meu_jogador': 'outfielderBlocks', 'sentido': 'direto'},
    {'stat_adversario': 'shotsOnTarget', 'stat_meu_jogador': 'clearances', 'sentido': 'direto'},
    {'stat_adversario': 'successfulDribbles', 'stat_meu_jogador': 'dribbledPast', 'sentido': 'inverso'},
    {'stat_adversario': 'aerialDuelsWon', 'stat_meu_jogador': 'aerialDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'groundDuelsWon', 'stat_meu_jogador': 'groundDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'goalsFromInsideTheBox', 'stat_meu_jogador': 'clearances', 'sentido': 'direto'},
    {'stat_adversario': 'headedGoals', 'stat_meu_jogador': 'aerialDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'accurateFinalThirdPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'possessionWonAttThird', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'keyPasses', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'keyPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
]

MATCHUP_PONTA_VS_LATERAL = [
    {'stat_adversario': 'successfulDribbles', 'stat_meu_jogador': 'dribbledPast', 'sentido': 'inverso'},
    {'stat_adversario': 'accurateCrosses', 'stat_meu_jogador': 'clearances', 'sentido': 'direto'},
    {'stat_adversario': 'totalCross', 'stat_meu_jogador': 'clearances', 'sentido': 'direto'},
    {'stat_adversario': 'keyPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'groundDuelsWon', 'stat_meu_jogador': 'groundDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'aerialDuelsWon', 'stat_meu_jogador': 'aerialDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'assists', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'assists', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'accurateFinalThirdPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'shotsOnTarget', 'stat_meu_jogador': 'blockedShots', 'sentido': 'direto'},
    {'stat_adversario': 'possessionWonAttThird', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'totalShots', 'stat_meu_jogador': 'blockedShots', 'sentido': 'direto'},
    {'stat_adversario': 'goals', 'stat_meu_jogador': 'goalsConceded', 'sentido': 'inverso'},
]

MATCHUP_MEIA_VS_MEIA = [
    {'stat_adversario': 'keyPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'accuratePasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'accuratePasses', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'accurateFinalThirdPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'accurateOwnHalfPasses', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'accurateOppositionHalfPasses', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'assists', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'successfulDribbles', 'stat_meu_jogador': 'dribbledPast', 'sentido': 'inverso'},
    {'stat_adversario': 'groundDuelsWon', 'stat_meu_jogador': 'groundDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'aerialDuelsWon', 'stat_meu_jogador': 'aerialDuelsWon', 'sentido': 'direto'},
    {'stat_adversario': 'totalShots', 'stat_meu_jogador': 'blockedShots', 'sentido': 'direto'},
    {'stat_adversario': 'shotsOnTarget', 'stat_meu_jogador': 'blockedShots', 'sentido': 'direto'},
    {'stat_adversario': 'possessionWonAttThird', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'bigChancesCreated', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
    {'stat_adversario': 'bigChancesCreated', 'stat_meu_jogador': 'tackles', 'sentido': 'direto'},
    {'stat_adversario': 'accurateLongBalls', 'stat_meu_jogador': 'interceptions', 'sentido': 'direto'},
]

# --- EXPLORAÇÃO ---

MATCHUP_ZAGUEIRO_ADV_VS_MEU_ATACANTE = [
    {'stat_adversario': 'dribbledPast', 'stat_meu_jogador': 'successfulDribbles', 'sentido': 'direto'},
    {'stat_adversario': 'aerialDuelsWon', 'stat_meu_jogador': 'aerialDuelsWon', 'sentido': 'inverso'},
    {'stat_adversario': 'groundDuelsWon', 'stat_meu_jogador': 'groundDuelsWon', 'sentido': 'inverso'},
    {'stat_adversario': 'clearances', 'stat_meu_jogador': 'totalShots', 'sentido': 'direto'},
    {'stat_adversario': 'tackles', 'stat_meu_jogador': 'successfulDribbles', 'sentido': 'direto'},
    {'stat_adversario': 'interceptions', 'stat_meu_jogador': 'keyPasses', 'sentido': 'direto'},
    {'stat_adversario': 'blockedShots', 'stat_meu_jogador': 'shotsOnTarget', 'sentido': 'direto'},
    {'stat_adversario': 'goalsConceded', 'stat_meu_jogador': 'goals', 'sentido': 'direto'},
]

MATCHUP_LATERAL_ADV_VS_MINHA_PONTA = [
    {'stat_adversario': 'dribbledPast', 'stat_meu_jogador': 'successfulDribbles', 'sentido': 'direto'},
    {'stat_adversario': 'groundDuelsWon', 'stat_meu_jogador': 'groundDuelsWon', 'sentido': 'inverso'},
    {'stat_adversario': 'aerialDuelsWon', 'stat_meu_jogador': 'aerialDuelsWon', 'sentido': 'inverso'},
    {'stat_adversario': 'tackles', 'stat_meu_jogador': 'successfulDribbles', 'sentido': 'direto'},
    {'stat_adversario': 'interceptions', 'stat_meu_jogador': 'keyPasses', 'sentido': 'direto'},
    {'stat_adversario': 'clearances', 'stat_meu_jogador': 'accurateCrosses', 'sentido': 'direto'},
    {'stat_adversario': 'blockedShots', 'stat_meu_jogador': 'shotsOnTarget', 'sentido': 'direto'},
    {'stat_adversario': 'accurateCrosses', 'stat_meu_jogador': 'interceptions', 'sentido': 'inverso'},
    {'stat_adversario': 'goalsConceded', 'stat_meu_jogador': 'goals', 'sentido': 'direto'},
]

MATCHUP_POR_ARQUETIPO = {
    4: MATCHUP_LATERAL_ADV_VS_MINHA_PONTA,
    5: MATCHUP_LATERAL_ADV_VS_MINHA_PONTA,
    6: MATCHUP_LATERAL_ADV_VS_MINHA_PONTA,
    7: MATCHUP_LATERAL_ADV_VS_MINHA_PONTA,
    8: MATCHUP_LATERAL_ADV_VS_MINHA_PONTA,
    9: MATCHUP_ZAGUEIRO_ADV_VS_MEU_ATACANTE,
    10: MATCHUP_ZAGUEIRO_ADV_VS_MEU_ATACANTE,
    11: MATCHUP_ZAGUEIRO_ADV_VS_MEU_ATACANTE,
    12: MATCHUP_ZAGUEIRO_ADV_VS_MEU_ATACANTE,
    13: MATCHUP_MEIA_VS_MEIA, 14: MATCHUP_MEIA_VS_MEIA,
    15: MATCHUP_MEIA_VS_MEIA, 16: MATCHUP_MEIA_VS_MEIA,
    17: MATCHUP_MEIA_VS_MEIA, 18: MATCHUP_MEIA_VS_MEIA,
    19: MATCHUP_MEIA_VS_MEIA, 20: MATCHUP_MEIA_VS_MEIA,
    21: MATCHUP_MEIA_VS_MEIA, 22: MATCHUP_MEIA_VS_MEIA,
    23: MATCHUP_MEIA_VS_MEIA, 24: MATCHUP_MEIA_VS_MEIA,
    25: MATCHUP_MEIA_VS_MEIA, 26: MATCHUP_MEIA_VS_MEIA,
    27: MATCHUP_PONTA_VS_LATERAL, 28: MATCHUP_PONTA_VS_LATERAL,
    29: MATCHUP_PONTA_VS_LATERAL, 30: MATCHUP_PONTA_VS_LATERAL,
    31: MATCHUP_PONTA_VS_LATERAL, 32: MATCHUP_PONTA_VS_LATERAL,
    33: MATCHUP_PONTA_VS_LATERAL,
    34: MATCHUP_ATACANTE_VS_ZAGUEIRO, 35: MATCHUP_ATACANTE_VS_ZAGUEIRO,
    36: MATCHUP_ATACANTE_VS_ZAGUEIRO, 37: MATCHUP_ATACANTE_VS_ZAGUEIRO,
}

ARQUETIPO_COUNTER_IDS = {
    4: [31, 32, 33, 27, 28, 29, 30],
    5: [31, 32, 33, 27, 28, 29, 30],
    6: [31, 32, 33, 27, 28, 29, 30],
    7: [31, 32, 33, 27, 28, 29, 30],
    8: [31, 32, 33, 27, 28, 29, 30],
    9: [34, 35, 36, 37],
    10: [34, 35, 36, 37],
    11: [34, 35, 36, 37],
    12: [34, 35, 36, 37],
    13: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    14: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    15: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    16: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    17: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    18: [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    19: [19, 20, 21, 22, 23, 24, 25, 26],
    20: [19, 20, 21, 22, 23, 24, 25, 26],
    21: [19, 20, 21, 22, 23, 24, 25, 26],
    22: [19, 20, 21, 22, 23, 24, 25, 26],
    23: [19, 20, 21, 22, 23, 24, 25, 26],
    24: [19, 20, 21, 22, 23, 24, 25, 26],
    25: [19, 20, 21, 22, 23, 24, 25, 26],
    26: [19, 20, 21, 22, 23, 24, 25, 26],
    27: [4, 5, 6, 7, 8],
    28: [4, 5, 6, 7, 8],
    29: [4, 5, 6, 7, 8],
    30: [4, 5, 6, 7, 8],
    31: [4, 5, 6, 7, 8],
    32: [4, 5, 6, 7, 8],
    33: [4, 5, 6, 7, 8],
    34: [9, 10, 11, 12],
    35: [9, 10, 11, 12],
    36: [9, 10, 11, 12],
    37: [9, 10, 11, 12],
}

ARQUETIPOS_GOLEIRO = {1, 2, 3}